name: recyclopedia
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  json_annotation: ^4.8.0
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.2.0
  google_maps_flutter_android: ^2.1.10
  google_maps_flutter_ios: ^2.1.10
  google_maps_flutter_platform_interface: ^2.2.1
  google_maps_flutter_web: ^0.4.0
  provider: ^6.0.2
  uuid: ^3.0.4
  go_router: ^6.0.0
  collection: ^1.16.0
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  english_words: ^4.0.0
  url_launcher: ^6.1.7
  http: ^0.13.6

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.0
  flutter_test:
    sdk: flutter
  test: ^1.22.0

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  plugin:
    platforms:
      android:
        default_package: google_maps_flutter_android
      ios:
        default_package: google_maps_flutter_ios
